# Generated by Django 6.0.6 on 2026-07-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_comment_proposal'),
        ('events', '0002_remove_event_proposal_event_poll'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        # constraint must go before the field it spans (autogen ordered these wrong)
        migrations.AlterUniqueTogether(
            name='proposalvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proposalvote',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposalvote',
            name='member',
        ),
        migrations.DeleteModel(
            name='ProposalVote',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
