# Generated by Django 6.0.6 on 2026-07-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_allow_multiple_poll_kind_slot_date_end_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['position', 'created_at']},
        ),
        migrations.AddField(
            model_name='option',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
