# Generated by Django 6.0.6 on 2026-07-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_option_options_option_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
