# Generated by Django 6.0.6 on 2026-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_locked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='kind',
            field=models.CharField(choices=[('choice', 'Choice'), ('date', 'Date'), ('range', 'Range')], default='choice', max_length=8),
        ),
    ]
