# Generated by Django 6.0.6 on 2026-07-05 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('polls', '0002_poll_allow_multiple_poll_kind_slot_date_end_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='proposal',
        ),
        migrations.AddField(
            model_name='event',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='polls.poll'),
        ),
    ]
