# Generated by Django 6.0.6 on 2026-07-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_display_name_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
