# Generated by Django 6.0.6 on 2026-07-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seen_changelog_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
