# Generated by Django 6.0.6 on 2026-07-05 08:02

import apps.activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='short_id',
            field=models.CharField(db_index=True, default=apps.activities.models._short_id, max_length=6, unique=True),
        ),
    ]
