# Generated by Django 6.0.6 on 2026-07-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_short_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='proposal',
        ),
    ]
