# Generated by Django 6.0.6 on 2026-07-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_comment_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
