# Generated by Django 6.0.6 on 2026-07-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
