# Generated by Django 6.0.6 on 2026-07-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
